## Local Zeebe Cluster
zeebe:
  audience: zeebe-api
  client:
    broker:
      grpc-address: https://grpc-zeebe.c8.local
      rest-address: https://c8.local/zeebe
    cloud:
      auth-url: https://c8.local/auth/realms/camunda-platform/protocol/openid-connect/token
      client-id: zeebe
      client-secret: Camunda1
    connection-mode: ADDRESS
    security:
      cert-path: /home/administrator/software/camunda/camunda-platform-8/certificates/c8.crt
      plaintext: false
    worker:
      max-jobs-active: 32
      threads: 2

logging:
  #  file:
  #    path: ./logs           # specify a path to write to file, otherwise it defaults to the console.
  level:
    org.example: INFO
    org.example.c8: DEBUG
